### ISSUE TITLE
`@schema` throws when we inherit an empty class

### ISSUE THREAD

**Issue by botflux** [GiovanniCardamone/class-schema#5]
Hello, 

As I was writing the test for #4, I discovered that the `@schema` decorator throws a `TypeError` when the parent class has
no props. In practice, this bug shouldn't append that much but when I got it I didn't really understand what was happening.

```typescript
import 'reflect-metadata'
import { prop, schema, use } from "class-schema";

@schema()
class ParentSchema {
}

// ⬇️ This one is throwing
@schema()
class ChildSchema extends ParentSchema {}
```

The stack trace is something like this:

```
     TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
      at __read (node_modules/class-schema/dist/decorators/schema.js:14:46)
      at /Users/v-mendele/Documents/projects/repro-class-schema/node_modules/class-schema/src/decorators/schema.ts:27:16
      at DecorateConstructor (node_modules/reflect-metadata/Reflect.js:541:33)
      at Reflect.decorate (node_modules/reflect-metadata/Reflect.js:130:24)
      at __decorate (test.ts:4:92)
      at Context.<anonymous> (test.ts:11:22)
      at processImmediate (node:internal/timers:473:21)
```

The trace points [this line](https://github.com/GiovanniCardamone/class-schema/blob/efd879a402e1b3ded59dce7576de09aa7b370010/src/decorators/schema.ts#L27), maybe the array is not initialized, I didn't dig into it.

I made a [reproduction repository](https://github.com/botflux/class-schema-inherited-schema-bug) with two test cases.
I can fix it if you want.

Have a nice day!

**Comment by GiovanniCardamone** [comment]
yes, i think because an array with props is added when a prop is inserted in a schema.

Using inheritance is trying to iterate undefined, so that's why it throws the error, I'll solve it soon (this week end at least), can you add a property rn for avoid this behavior?

**Comment by botflux** [comment]
I did it, no problem :)
